name: ReactiveX
markdown: redcarpet
safe: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
baseurl: "/reactivex.github.io"
lsi: false
